version: '3.8'

# for postgres
services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # for backend of the application
  backend:
    build:
      context: ./backend
      container_name: backend
      restart: always
      ports:
        - "8000:8000"
      depends_on:
        - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - ./backend:/app


volumes:
  db_data: